name: stream_feed_flutter_core
description: Stream Feed official Flutter SDK Core. Build your own feed experience using Dart and Flutter.
version: 0.8.0
repository: https://github.com/GetStream/stream-feed-flutter
issue_tracker: https://github.com/GetStream/stream-feed-flutter/issues
homepage: https://getstream.io/
publish_to: 'none'
environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  stream_feed:
    path: ../stream_feed

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.1.1
  equatable: ^2.0.3
  meta: ^1.8.0
  rxdart: ^0.27.1

  collection: ^1.15.0
  faye_dart: ^0.1.1+2
  http_parser: ^4.0.0
  intl: ^0.17.0
  jose: ^0.3.2
  json_annotation: ^4.4.0
  logging: ^1.0.1
  mime: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.3.0
  build_runner: ^2.0.2
  json_serializable: ^6.1.5
  test: ^1.17.3
